# Image Operations
> 1. https://docs.opencv.org/4.x/da/df6/tutorial_py_table_of_contents_setup.html
> 2. https://docs.opencv.org/4.x/dc/d4d/tutorial_py_table_of_contents_gui.html

In [2]:
# cv2 ve numpy kütüphanelerini ekliyoruz
import cv2
import numpy as np

Burada, **cv2** kütüphanesini OpenCV işlevselliğine erişim sağlamak için ve **numpy** kütüphanesini çok boyutlu dizilerle çalışmak için ekliyorsunuz.

#### Görüntü Okuma (cv2.imread)

In [3]:
# 'cat.jpg', 'dog.jpg', 'duck.jpg', ve 'klon.jpg' dosyalarından görüntüleri okuyoruz
img_cat = cv2.imread("test_images/cat.jpg")
img_dog = cv2.imread("test_images/dog.jpg")
img_duck = cv2.imread("test_images/duck.jpg")
img_klon = cv2.imread("test_images/klon.jpg")

Bu kod bloğunda, **cv2.imread()** fonksiyonu kullanılarak dört farklı dosyadan (cat.jpg, dog.jpg, duck.jpg ve klon.jpg) görüntü okunuyor. Her bir görüntü, sırasıyla img_cat, img_dog, img_duck ve img_klon adlı değişkenlere atanıyor.

cv2.imread() fonksiyonu, *belirtilen dosya adındaki görüntüyü okur ve bir NumPy dizisi olarak döndürür*. Bu diziyi daha sonra görüntü işleme işlemlerinde kullanabilirsiniz.

In [4]:
print(img_cat,img_dog,img_duck,img_klon)

[[[ 99  98 102]
  [100  99 103]
  [101 100 104]
  ...
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[100  99 103]
  [100  99 103]
  [101 100 104]
  ...
  [ 37  37  37]
  [ 36  36  36]
  [ 36  36  36]]

 [[101 100 102]
  [101 100 102]
  [102 101 103]
  ...
  [ 36  36  36]
  [ 35  35  35]
  [ 35  35  35]]

 ...

 [[ 88  87  89]
  [ 88  87  89]
  [ 87  86  88]
  ...
  [ 74  71  73]
  [ 72  69  71]
  [ 71  68  70]]

 [[ 86  85  87]
  [ 86  85  87]
  [ 85  84  86]
  ...
  [ 75  72  74]
  [ 73  70  72]
  [ 72  69  71]]

 [[ 86  85  87]
  [ 86  85  87]
  [ 86  85  87]
  ...
  [ 76  73  75]
  [ 74  71  73]
  [ 72  69  71]]] [[[ 62  83 114]
  [ 57  78 109]
  [ 55  76 104]
  ...
  [146 153 162]
  [146 155 164]
  [145 154 163]]

 [[ 60  81 112]
  [ 64  85 116]
  [ 66  86 117]
  ...
  [147 154 163]
  [146 155 164]
  [144 153 162]]

 [[ 55  78 110]
  [ 64  88 118]
  [ 71  92 123]
  ...
  [150 157 166]
  [150 159 168]
  [151 160 169]]

 ...

 [[ 56  69  83]
  [ 56  69  83]
  [ 56  69  85]
  ..

cv2.imread() ile okunan görüntüler, NumPy dizileri olarak temsil edilir. Eğer bu dizileri doğrudan **print()** ile bastırırsanız, her bir pikselin renk değerlerini içeren bir matris göreceksiniz. 

In [5]:
# Görüntülerin boyutları ve türleri
print("Cat Image Shape:", img_cat.shape, "Data Type:", img_cat.dtype)
print("Dog Image Shape:", img_dog.shape, "Data Type:", img_dog.dtype)
print("Duck Image Shape:", img_duck.shape, "Data Type:", img_duck.dtype)
print("Klon Image Shape:", img_klon.shape, "Data Type:", img_klon.dtype)

Cat Image Shape: (853, 1280, 3) Data Type: uint8
Dog Image Shape: (853, 1280, 3) Data Type: uint8
Duck Image Shape: (853, 1280, 3) Data Type: uint8
Klon Image Shape: (426, 640, 3) Data Type: uint8


Bu, her bir görüntünün boyutlarını (shape) ve veri türünü (dtype) ekrana basacaktır. Eğer matris içeriğini görmek istiyorsanız, örneğin, sadece ilk satır ve sütunları göstermek için şu şekilde yapabilirsiniz:

#### Özel Ayarlar 

In [6]:
cv2.namedWindow("Image",cv2.WINDOW_NORMAL) # -> Normal boyutta bir pencere oluştur 
cv2.namedWindow("Image",cv2.WINDOW_FULLSCREEN) # -> Tam ekran boyutunda bir pencere oluştur
# cv2.namedWindow("Image",(600,600)) # -> Pencere açıldığında 600x600 noktasından açılacak
cv2.namedWindow("Image",cv2.WINDOW_AUTOSIZE) # -> Otomatik boyut ayarlamalı bir pencere oluştur

**cv2.namedWindow** fonksiyonu, açılacak pencere için özel ayarlar eklememizi sağlar. İlk virgülde pencereye bir isim veririz. İkinci virgülde, pencerenin özelliklerini belirleyebiliriz. Gerekirse, üçüncü virgül ve sonrasında ek ayarlamalar yapabiliriz.

In [7]:
new_width = 300
new_height = 200
resized_image_1 = cv2.resize(img_cat, (new_width, new_height))

Bu örnekte, resize fonksiyonuyla resmin boyutu belirli bir genişlik (new_width) ve yükseklik (new_height) değerine göre ayarlanmıştır. Bu, resmin kesin bir genişlik ve yüksekliğe sahip olmasını sağlar. Ancak, orijinal resmin oranı değişebilir.

#### Görüntü Gösterme (cv2.imshow)

In [8]:
cv2.imshow("Image",img_cat)
cv2.imshow("Image",img_dog)
cv2.imshow("Image",img_duck)
cv2.imshow("Image",img_klon)

**cv2.imshow** Fonksiyonumuz ilk virgülde pencere ismi veriyoruz ikinci virgülde ise hangi resmi göstereceğimizi seçeriz ve sonuç bize o resmi gösterecektir. (pencereye özellikler vermişsek önceden o pencere adı ile aynı olmalıdır buradaki pencere adı)

#### Görüntü Kaydetme (cv2.imwrite)

In [9]:
cv2.imwrite("cat1.jpg",img_cat)
cv2.imwrite("dog1.jpg",img_dog)
cv2.imwrite("duck1.jpg",img_duck)
cv2.imwrite("klon1.jpg",img_klon)

True

**cv2.imwrite** Fonksiyonu ilk virgülde kaydedilecek yeni dosya adı ve ikinci virgülde hangi değişkenin veya işlenen verinin o dosya yoluna kaydedileceğini seçiyoruz, yani *amacı işlenmiş olan görselleri kaydetmektir*.

In [10]:
cv2.waitKey(0)
cv2.destroyAllWindows()

- cv2.waitKey(0) fonksiyonu, bir klavye girişini bekler. Programınız, bu satıra geldiğinde bir tuşa basılmasını bekleyecektir. Parametre olarak verilen değer (0), sonsuza kadar bekleme anlamına gelir. Bu sayede, bir tuşa basılana kadar program durur.

- cv2.destroyAllWindows() fonksiyonu ise açık olan tüm OpenCV pencerelerini kapatır. Bu fonksiyon, cv2.waitKey fonksiyonu tarafından beklenen bir tuşa basılma olayı gerçekleştiğinde genellikle kullanılır. Yani, eğer bir tuşa basıldıktan sonra pencereleri kapatmak istiyorsanız, cv2.destroyAllWindows() fonksiyonunu çağırabilirsiniz.